### ISSUE TITLE
[feature] make a sideload app to boot in second or the first ios

### ISSUE THREAD

**Issue by peterProgramer** [edwin170/dualra1n#10]

**Comment by edwin170** [comment]
> 

I don't understand could you explain Better please

**Comment by peterProgramer** [comment]
like a sideloaded app that allow you to boot to second ios

**Comment by peterProgramer** [comment]
on both ios

**Comment by peterProgramer** [comment]
instead of use --boot command on mac/linux you can so i straight from the device
