### ISSUE TITLE
git URL is wrong

### ISSUE THREAD

**Issue by danni5512** [edwin170/dualra1n#9]
Every time I run the script this error comes:

[*] Command ran: ./dualboot.sh --dualboot 14.3 --jail_palera1n
curl installed
fatal: not a git repository (or any of the parent directories): .git

**Comment by edwin170** [comment]
It is because I changed the name of the dualboot to dualra1n so you have to save the ipsw and delete the dualboot directory and git clone again

**Comment by edwin170** [comment]
> Every time I run the script this error comes:
> 
> 
> 
> [*] Command ran: ./dualboot.sh --dualboot 14.3 --jail_palera1n
> 
> curl installed
> 
> fatal: not a git repository (or any of the parent directories): .git
> 
> 
> 
> 

And paste the ipsw after git clone

**Comment by edwin170** [comment]
> Every time I run the script this error comes:
> 
> 
> 
> [*] Command ran: ./dualboot.sh --dualboot 14.3 --jail_palera1n
> 
> curl installed
> 
> fatal: not a git repository (or any of the parent directories): .git
> 
> 
> 
> 

If you are ok Linux 
You have to install this https://github.com/darlinghq/darling maybe for that reason is the error
